name: autoversion

on:
  workflow_dispatch:
    inputs:
      version-segment:
        description: Version segment
        required: true
        type: choice
        options:
          - patch
          - minor

jobs:
  release:
    env:
      VERSION_SEGMENT: ${{ github.event.inputs.version-segment }}
      GH_TOKEN: ${{ github.GH_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Publish release on github
      run: |
        CHANGELOG=$(hatch version $VERSION_SEGMENT)
        echo "$CHANGELOG" >> $GITHUB_ENV
        TAG=$(hatch version)
        git config --global user.email "auto@version"
        git config --global user.name "autoversion"
        git commit -am "Release: $TAG
        
        $CHANGELOG"
        git tag "$TAG"
        git push && git push --tags
        gh release create $TAG --title "$TAG" --notes "$CHANGELOG"
#    - name: Build package
#      run: hatch build
#    - name: Publish package
#      run: |
#        hatch publish -u __token__ -a ${{ secrets.PYPI_API_TOKEN }}
